// Flags of the place groups (public/flags/<key>.png): Wikimedia Commons renders
// of each community's and province's flag, with the attribution their licences ask
// for (shown in Créditos). Places without an official flag use their community's.
export const FLAG_CREDITS = [
  { key: 'es-andalucia', file: 'Flag of Andalucía.svg', author: 'Miguillen This picture was made for the Taller de Heráldica y vexilología of Spanish Wikipedia.', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Andaluc%C3%ADa.svg' },
  { key: 'es-almeria', file: 'Flag Almería Province.svg', author: 'Almju', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_Almer%C3%ADa_Province.svg' },
  { key: 'es-cadiz', file: 'Flag Cádiz Province.svg', author: 'Ulaidh', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_C%C3%A1diz_Province.svg' },
  { key: 'es-cordoba', file: 'Provincia de Córdoba - Bandera.svg', author: 'HansenBCN', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Provincia_de_C%C3%B3rdoba_-_Bandera.svg' },
  { key: 'es-granada', file: 'Bandera de la provincia de Granada (España).svg', author: 'Erlenmeyer', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_la_provincia_de_Granada_(Espa%C3%B1a).svg' },
  { key: 'es-huelva', file: 'Bandera de la Provincia De Huelva.svg', author: 'Wikimedia Commons', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_la_Provincia_De_Huelva.svg' },
  { key: 'es-jaen', file: 'Bandera de la provincia de Jaén.svg', author: 'User:Juancharlie', license: 'CC BY 2.5', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_la_provincia_de_Ja%C3%A9n.svg' },
  { key: 'es-malaga', file: 'Flag Málaga Province.svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_M%C3%A1laga_Province.svg' },
  { key: 'es-sevilla', file: 'Flag of Diputacion de Sevilla Spain.svg', author: 'Apj (Taller de Heráldica y Vexilología in the Spanish Wikipedia )', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Diputacion_de_Sevilla_Spain.svg' },
  { key: 'es-aragon', file: 'Flag of Aragon.svg', author: 'Wikimedia Commons', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Aragon.svg' },
  { key: 'es-huesca', file: 'Flag of Huesca (province).svg', author: 'Willtron', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Huesca_(province).svg' },
  { key: 'es-teruel', file: 'Flag of Teruel (province).svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Teruel_(province).svg' },
  { key: 'es-zaragoza', file: 'Bandera de la provincia de Zaragoza.svg', author: 'David Ll L', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_la_provincia_de_Zaragoza.svg' },
  { key: 'es-asturias', file: 'Flag of Asturias.svg', author: 'Banderas', license: 'Public domain', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Asturias.svg' },
  { key: 'es-baleares', file: 'Flag of the Balearic Islands.svg', author: 'Wikimedia Commons', license: 'CC0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_the_Balearic_Islands.svg' },
  { key: 'es-canarias', file: 'Flag of the Canary Islands.svg', author: 'No machine-readable author provided. Zirland assumed (based on copyright claims).', license: 'Public domain', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_the_Canary_Islands.svg' },
  { key: 'es-las-palmas', file: 'Provincia de Las Palmas - Bandera.svg', author: 'HansenBCN', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Provincia_de_Las_Palmas_-_Bandera.svg' },
  { key: 'es-santa-cruz-de-tenerife', file: 'Provincia de Santa Cruz de Tenerife - Bandera.svg', author: 'HansenBCN', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Provincia_de_Santa_Cruz_de_Tenerife_-_Bandera.svg' },
  { key: 'es-cantabria', file: 'Flag of Cantabria (Official).svg', author: 'Miguillen', license: 'CC BY-SA 2.5', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Cantabria_(Official).svg' },
  { key: 'es-castilla-la-mancha', file: 'Flag of Castile-La Mancha.svg', author: 'Xinese-v', license: 'Public domain', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Castile-La_Mancha.svg' },
  { key: 'es-albacete', file: 'Bandera provincia Albacete.svg', author: 'Espanish AlB; SanchoPanzaXXI; HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_provincia_Albacete.svg' },
  { key: 'es-ciudad-real', file: 'Flag Ciudad Real Province.svg', author: 'Ulaidh', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_Ciudad_Real_Province.svg' },
  { key: 'es-cuenca', file: 'Flag Cuenca Province.svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_Cuenca_Province.svg' },
  { key: 'es-guadalajara', file: 'Bandera de la Provincia de Guadalajara.svg', author: 'David Ll L', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_la_Provincia_de_Guadalajara.svg' },
  { key: 'es-toledo', file: 'Bandera de la provincia de Toledo.svg', author: 'Asqueladd', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_la_provincia_de_Toledo.svg' },
  { key: 'es-castilla-y-leon', file: 'Flag of Castile and León.svg', author: 'Rastrojo (D•ES)', license: 'CC BY 3.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Castile_and_Le%C3%B3n.svg' },
  { key: 'es-avila', file: 'Bandera de la provincia de Ávila.svg', author: 'Rastrojo (D•ES)', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_la_provincia_de_%C3%81vila.svg' },
  { key: 'es-burgos', file: 'Flag Burgos Province.svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_Burgos_Province.svg' },
  { key: 'es-leon', file: 'Flag León Province.svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_Le%C3%B3n_Province.svg' },
  { key: 'es-palencia', file: 'Bandera de la provincia de Palencia1.svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_la_provincia_de_Palencia1.svg' },
  { key: 'es-salamanca', file: 'Bandera de la provincia de Salamanca.svg', author: 'HansenBCN', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_la_provincia_de_Salamanca.svg' },
  { key: 'es-segovia', file: 'Flag Segovia province.svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_Segovia_province.svg' },
  { key: 'es-soria', file: 'Flag Soria province.svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_Soria_province.svg' },
  { key: 'es-valladolid', file: 'Bandera de la provincia de Valladolid.svg', author: 'Original: Vexilla Hispanica. Vectorization: Chabacano', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_la_provincia_de_Valladolid.svg' },
  { key: 'es-cataluna', file: 'Flag of Catalonia.svg', author: 'Motoroil', license: 'Public domain', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Catalonia.svg' },
  { key: 'es-barcelona', file: 'Flag of Barcelona (province).svg', author: 'Wikimedia Commons', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Barcelona_(province).svg' },
  { key: 'es-tarragona', file: 'Bandera actual de la provincia de Tarragona (alternate).svg', author: 'Original version by HansenBCN', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_actual_de_la_provincia_de_Tarragona_(alternate).svg' },
  { key: 'es-ceuta', file: 'Flag of Ceuta.svg', author: 'Ulaidh', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Ceuta.svg' },
  { key: 'es-comunitat-valenciana', file: 'Flag of the Land of Valencia (official).svg', author: 'Mutxamel', license: 'Public domain', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_the_Land_of_Valencia_(official).svg' },
  { key: 'es-extremadura', file: 'Flag of Extremadura, Spain (with coat of arms).svg', author: 'BetacommandBot', license: 'Public domain', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Extremadura,_Spain_(with_coat_of_arms).svg' },
  { key: 'es-badajoz', file: 'Provincia de Badajoz - Bandera.svg', author: 'HansenBCN', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Provincia_de_Badajoz_-_Bandera.svg' },
  { key: 'es-caceres', file: 'Flag of the province of Cáceres.svg', author: 'Ewan ar Born, Rastrojo and Offnfopt', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_the_province_of_C%C3%A1ceres.svg' },
  { key: 'es-galicia', file: 'Flag of Galicia.svg', author: 'Pedro A. Gracia Fajardo', license: 'Public domain', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Galicia.svg' },
  { key: 'es-lugo', file: 'Flag of Lugo province.svg', author: 'Ulaidh', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Lugo_province.svg' },
  { key: 'es-ourense', file: 'Provincia de Ourense - Bandera.svg', author: 'HansenBCN', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Provincia_de_Ourense_-_Bandera.svg' },
  { key: 'es-pontevedra', file: 'Flag Pontevedra Province.svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_Pontevedra_Province.svg' },
  { key: 'es-madrid', file: 'Flag of the Community of Madrid.svg', author: 'See file history', license: 'CC0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_the_Community_of_Madrid.svg' },
  { key: 'es-melilla', file: 'Flag of Melilla.svg', author: 'Wikimedia Commons', license: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Melilla.svg' },
  { key: 'es-murcia', file: 'Flag of the Region of Murcia.svg', author: 'Wikimedia Commons', license: 'CC0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_the_Region_of_Murcia.svg' },
  { key: 'es-navarra', file: 'Flag of Navarre.svg', author: 'Miguillen Insignia This image shows a flag, a coat of arms, a seal or some other official insignia. The use of such symb', license: 'Public domain', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Navarre.svg' },
  { key: 'es-pais-vasco', file: 'Flag of the Basque Country.svg', author: 'Daniele Schirmo aka Frankie688', license: 'CC BY-SA 2.5', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_the_Basque_Country.svg' },
  { key: 'es-alava', file: 'Flag of Álava.svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_%C3%81lava.svg' },
  { key: 'es-bizkaia', file: 'Bandera de Vizcaya.svg', author: 'SanchoPanzaXXI', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Bandera_de_Vizcaya.svg' },
  { key: 'es-gipuzkoa', file: 'Flag of Guipúzcoa.svg', author: 'HansenBCN', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_Guip%C3%BAzcoa.svg' },
  { key: 'es-la-rioja', file: 'Flag of La Rioja (with coat of arms).svg', author: 'jynus', license: 'CC BY 2.5', url: 'https://commons.wikimedia.org/wiki/File:Flag_of_La_Rioja_(with_coat_of_arms).svg' },
]

/** Places with a flag of their own. */
export const FLAG_KEYS = new Set(FLAG_CREDITS.map((f) => f.key))
